# Generated by Django 6.0.5 on 2026-07-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='bird_age',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='bird_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='conversation_state',
            field=models.CharField(default='WELCOME', max_length=50),
        ),
        migrations.AddField(
            model_name='farmer',
            name='current_vet_consultation_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='has_iot_device',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmer',
            name='iot_device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
