from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from drf_yasg.utils import swagger_auto_schema
from drf_yasg import openapi

from django.http import HttpResponse
from .models import Farmer, Conversation, HealthCase 
import requests 
import os
import time
from dotenv import load_dotenv

load_dotenv(override=True)



def get_ai_response(farmer, message_text):
    """
    Calls Agricare AI API to get the poultry advisory response.
    
    """
    
    raw_key = os.environ.get("AI_API_KEY") or os.environ.get("AGRICARE_API_KEY", "")
    api_key = raw_key.strip().replace('\r', '').replace('\n', '')

    if not api_key:
        print("SECURITY ERROR: No API KEY found! Check your .env file for AI_API_KEY.")
        return "I'm currently experiencing a high volume of queries. Please try again in a moment.", False

    masked_key = f"{api_key[:4]}...{api_key[-4:]}" if len(api_key) > 8 else "INVALID_KEY"
    print(f"SECURE LOG: API Key successfully verified and loaded (Active Key: {masked_key})")

    url = os.environ.get("AI_ENGINE_URL", "https://mirah003-agricare-ai-api.hf.space/generateContent")

    headers = {
        "X-API-Key": api_key,
        "Content-Type": "application/json"
    }

    context_msg = (
        f"Context - Farmer Name: {farmer.name or 'Unknown'}, "
        f"Bird Type: {farmer.bird_type or 'Unknown'}, "
        f"Bird Age: {farmer.bird_age or 'Unknown'}, "
        f"Flock Size: {farmer.flock_size or 'Unknown'}, "
        f"Location: {farmer.location or 'Unknown'}.\n\n"
        f"User's Question: {message_text}"
    )

    payload = {
        "query": context_msg
    }


    # Exponential Backoff Implementation 
    for delay in [1, 2, 4]:
        try: 
            print(f"SECURE LOG: Sending request to Agricare AI: '{message_text[:30]}...'" )
            response = requests.post(url, json=payload, headers=headers, timeout=15)
            print(f"DEBUG: Agricare AI server status code = {response.status_code}")
            if response.status_code == 200:
                result = response.json()
                ai_text = result.get("answer", "No response generated by the model.")

                # HITL / Check High risk case 
                is_high_risk = (
                    "[URGENT]" in ai_text
                    or "Newcastle" in ai_text.lower()
                    or "coccidiosis" in ai_text.lower()
                    or "gumboro" in ai_text.lower()
                )
                print(f"SECURE LOG: Agricare AI Diagnostic query response processed successfully. Risk Level = {is_high_risk}")
                return ai_text, is_high_risk
            # rate limit reached / time out 
            elif response.status_code == 403:
                print("SECURITY ERROR: 403 Forbidden. Check your AI_API_KEY inside your .env file.")
            elif response.status_code == 422:
                print(f"ERROR: 422 Unprocessable Entity. Payload error: {response.text}")

            else:
                print(f"ERROR: Agricare AI API returned unhandled status {response.status_code}")
                print(f"DEBUG RESPONSE: {response.text}")
                break

        except requests.exceptions.RequestException as e:
            print(f"RETRYING: Network or connection error: {str(e)}")
            time.sleep(delay)
            continue

        
    return "Our AI assistant is currently experiencing a high volume of queries. We have securely logged your issue and are activating the offline backup.", False

from twilio.rest import Client

class WhatsAppWebhookView(APIView):
    """
    FR-01: WhatsApp Conversational Advisory Interface.
    Handles incoming messages from Twilio Sandbox
    """

    @swagger_auto_schema(
        operation_description="Twilio WhatsApp API Webhook Receiver. Processes incoming messages.",
        responses={
            200: openapi.Response(description="Webhook processed successfully")
        }
    )
    def post(self, request):
        # Twilio sends form-encoded data
        body = request.data
        
        incoming_msg = body.get('Body', '').strip()
        from_number = body.get('From', '')
        profile_name = body.get('ProfileName', '')
        num_media = int(body.get('NumMedia', '0'))
        
        # Determine message type
        if num_media > 0:
            incoming_msg = "[Image Uploaded]"
            msg_type = "image"
        else:
            msg_type = "text"

        if not from_number or not incoming_msg:
            return Response({"error": "Missing message or sender"}, status=status.HTTP_400_BAD_REQUEST)
            
        # Strip "whatsapp:" if present in the from_number for internal storage, but keep it for replies
        db_phone = from_number.replace('whatsapp:', '')

        print(f"SECURE LOG: Webhook Received from phone: {db_phone} (Sender Profile Name: '{profile_name}')")  

        # get / create farmer (FR-11: Implicit onboarding) 
        farmer, created = Farmer.objects.get_or_create(phone_number=db_phone)

        if created or not farmer.name:
            if profile_name:
                farmer.name = profile_name
                farmer.save()
        
        # Log Farmer's Message (FR-01: History Retention)
        Conversation.objects.create(
            farmer=farmer,
            message_text=incoming_msg,
            sender_type='Farmer'
        )

        from .state_machine import process_message

        # We pass get_ai_response into the state machine for the Ask a Question state
        payloads_to_send = process_message(farmer, incoming_msg, message_type=msg_type, ai_func=get_ai_response)

        # Deliver response(s) back to farmer via Twilio WhatsApp API
        account_sid = os.environ.get("TWILIO_ACCOUNT_SID")
        auth_token = os.environ.get("TWILIO_AUTH_TOKEN")
        twilio_number = os.environ.get("TWILIO_WHATSAPP_NUMBER")
        
        if not account_sid or not auth_token or not twilio_number:
            print("ERROR: Twilio credentials not set. Cannot reply.")
            return Response({"status": "processed, but unable to reply (missing credentials)"}, status=status.HTTP_200_OK)

        client = Client(account_sid, auth_token)

        # Send all payloads sequentially
        for partial_payload in payloads_to_send:
            # Twilio doesn't use the JSON payload format, we just send text
            out_msg = partial_payload.get("text", {}).get("body", "[Text Message]")
            
            try:
                message = client.messages.create(
                    body=out_msg,
                    from_=twilio_number,
                    to=from_number
                )
                print(f"Twilio message sent: {message.sid}")
            except Exception as e:
                print(f"ERROR: Failed to send Twilio message: {e}")

            # Log AI response sent back
            Conversation.objects.create(
                farmer=farmer,
                message_text=out_msg,
                sender_type='AI'
            )

        # Twilio requires a 200 OK response
        return Response({"status": "success"}, status=status.HTTP_200_OK)
