from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from drf_yasg.utils import swagger_auto_schema
from drf_yasg import openapi

from django.http import HttpResponse
from .models import Farmer, Conversation, HealthCase 
import requests 
import os
import time
from dotenv import load_dotenv

load_dotenv(override=True)



def get_ai_response(farmer, message_text):
    """
    Calls Agricare AI API to get the poultry advisory response.
    
    """
    
    raw_key = os.environ.get("AI_API_KEY") or os.environ.get("AGRICARE_API_KEY", "")
    api_key = raw_key.strip().replace('\r', '').replace('\n', '')

    if not api_key:
        print("SECURITY ERROR: No API KEY found! Check your .env file for AI_API_KEY.")
        return "I'm currently experiencing a high volume of queries. Please try again in a moment.", False

    masked_key = f"{api_key[:4]}...{api_key[-4:]}" if len(api_key) > 8 else "INVALID_KEY"
    print(f"SECURE LOG: API Key successfully verified and loaded (Active Key: {masked_key})")

    url = os.environ.get("AI_ENGINE_URL", "https://mirah003-agricare-ai-api.hf.space/generateContent")

    headers = {
        "X-API-Key": api_key,
        "Content-Type": "application/json"
    }

    context_msg = (
        f"Context - Farmer Name: {farmer.name or 'Unknown'}, "
        f"Bird Type: {farmer.bird_type or 'Unknown'}, "
        f"Bird Age: {farmer.bird_age or 'Unknown'}, "
        f"Flock Size: {farmer.flock_size or 'Unknown'}, "
        f"Location: {farmer.location or 'Unknown'}.\n\n"
        f"User's Question: {message_text}"
    )

    payload = {
        "query": context_msg
    }


    # Exponential Backoff Implementation 
    for delay in [1, 2, 4]:
        try: 
            print(f"SECURE LOG: Sending request to Agricare AI: '{message_text[:30]}...'" )
            response = requests.post(url, json=payload, headers=headers, timeout=15)
            print(f"DEBUG: Agricare AI server status code = {response.status_code}")
            if response.status_code == 200:
                result = response.json()
                ai_text = result.get("answer", "No response generated by the model.")

                # HITL / Check High risk case 
                is_high_risk = (
                    "[URGENT]" in ai_text
                    or "Newcastle" in ai_text.lower()
                    or "coccidiosis" in ai_text.lower()
                    or "gumboro" in ai_text.lower()
                )
                print(f"SECURE LOG: Agricare AI Diagnostic query response processed successfully. Risk Level = {is_high_risk}")
                return ai_text, is_high_risk
            # rate limit reached / time out 
            elif response.status_code == 403:
                print("SECURITY ERROR: 403 Forbidden. Check your AI_API_KEY inside your .env file.")
            elif response.status_code == 422:
                print(f"ERROR: 422 Unprocessable Entity. Payload error: {response.text}")

            else:
                print(f"ERROR: Agricare AI API returned unhandled status {response.status_code}")
                print(f"DEBUG RESPONSE: {response.text}")
                break

        except requests.exceptions.RequestException as e:
            print(f"RETRYING: Network or connection error: {str(e)}")
            time.sleep(delay)
            continue

        
    return "Our AI assistant is currently experiencing a high volume of queries. We have securely logged your issue and are activating the offline backup.", False

class WhatsAppWebhookView(APIView):
    """
    FR-01: WhatsApp Conversational Advisory Interface.
    Handles incoming messages from Twilio Sandbox
    """

    @swagger_auto_schema(
        operation_description="Meta WhatsApp Cloud API Webhook Receiver. Processes incoming JSON messages and sends AI response.",
        request_body=openapi.Schema(
            type=openapi.TYPE_OBJECT,
            required=['entry'],
            properties={
                'entry': openapi.Schema(type=openapi.TYPE_ARRAY, items=openapi.Schema(type=openapi.TYPE_OBJECT))
            }
        ),
        responses={
            200: openapi.Response(description="Webhook processed successfully")
        }
    )
    def post(self, request):
        # Meta WhatsApp Cloud API sends JSON payloads
        body = request.data

        # Check if this is a WhatsApp status update or an actual message
        try:
            entry = body.get('entry', [])[0]
            changes = entry.get('changes', [])[0]
            value = changes.get('value', {})
            
            # If there are no messages, it might be a status update (delivered, read)
            if 'messages' not in value:
                return Response({"status": "ignored"}, status=status.HTTP_200_OK)

            message_obj = value['messages'][0]
            from_number = message_obj.get('from')
            
            # Text messages have 'text' dict, interactive messages have 'interactive'
            if 'text' in message_obj:
                incoming_msg = message_obj['text'].get('body', '')
                msg_type = "text"
            elif 'interactive' in message_obj:
                interactive = message_obj['interactive']
                if interactive.get('type') == 'button_reply':
                    incoming_msg = interactive['button_reply'].get('title', '')
                elif interactive.get('type') == 'list_reply':
                    incoming_msg = interactive['list_reply'].get('title', '')
                else:
                    incoming_msg = ""
                msg_type = "text"
            elif 'image' in message_obj:
                incoming_msg = "[Image Uploaded]"
                msg_type = "image"
            else:
                incoming_msg = "[Unsupported message type]"
                msg_type = "unknown"

            # Extract profile name if available
            contacts = value.get('contacts', [])
            profile_name = ""
            if contacts:
                profile_name = contacts[0].get('profile', {}).get('name', '')

        except (IndexError, KeyError, TypeError):
            return Response({"error": "Invalid payload structure"}, status=status.HTTP_400_BAD_REQUEST)

        if not from_number or not incoming_msg:
            return Response({"error": "Missing message or sender"}, status=status.HTTP_400_BAD_REQUEST)
        
        print(f"SECURE LOG: Webhook Received from phone: {from_number} (Sender Profile Name: '{profile_name}')")  

        # get / create farmer (FR-11: Implicit onboarding) 
        farmer, created = Farmer.objects.get_or_create(phone_number=from_number)

        if created or not farmer.name:
            if profile_name:
                farmer.name = profile_name
                farmer.save()
        
        # Log Farmer's Message (FR-01: History Retention)
        Conversation.objects.create(
            farmer=farmer,
            message_text=incoming_msg,
            sender_type='Farmer'
        )

        from .state_machine import process_message

        # We pass get_ai_response into the state machine for the Ask a Question state
        payloads_to_send = process_message(farmer, incoming_msg, message_type=msg_type, ai_func=get_ai_response)

        # Deliver response(s) back to farmer via Meta WhatsApp API
        access_token = os.environ.get("WHATSAPP_TOKEN") or os.environ.get("META_WHATSAPP_TOKEN", "")
        phone_number_id = os.environ.get("WHATSAPP_PHONE_ID", "")
        
        if not access_token or not phone_number_id:
            print("ERROR: WHATSAPP_TOKEN or WHATSAPP_PHONE_ID not set. Cannot reply.")
            return Response({"status": "processed, but unable to reply (missing credentials)"}, status=status.HTTP_200_OK)

        meta_url = f"https://graph.facebook.com/v19.0/{phone_number_id}/messages"
        headers = {
            "Authorization": f"Bearer {access_token}",
            "Content-Type": "application/json"
        }

        # Send all payloads sequentially
        for partial_payload in payloads_to_send:
            full_payload = {
                "messaging_product": "whatsapp",
                "to": from_number,
                **partial_payload
            }
            try:
                resp = requests.post(meta_url, headers=headers, json=full_payload, timeout=10)
                if resp.status_code not in (200, 201):
                    print(f"ERROR: Failed to send WhatsApp message. Meta responded: {resp.text}")
            except Exception as e:
                print(f"ERROR: Network failure sending to Meta API: {e}")

            # Log AI response sent back
            if partial_payload.get("type") == "text":
                out_msg = partial_payload.get("text", {}).get("body", "[Text Message]")
            else:
                out_msg = f"[{partial_payload.get('type')} Message sent]"

            Conversation.objects.create(
                farmer=farmer,
                message_text=out_msg,
                sender_type='AI'
            )

        # Meta requires a 200 OK response immediately to acknowledge receipt
        return Response({"status": "success"}, status=status.HTTP_200_OK)
    
    @swagger_auto_schema(
        operation_description="Required verification endpoint for external Webhook setup. Validates secret tokens.",
        manual_parameters=[
            openapi.Parameter(
                name='hub.mode',
                in_=openapi.IN_QUERY,
                type=openapi.TYPE_STRING,
                required=True,
                description="The webhook mode sent by the provider. Always use 'subscribe'.",
                example="subscribe"
            ),
            openapi.Parameter(
                name='hub.verify_token',
                in_=openapi.IN_QUERY,
                type=openapi.TYPE_STRING,
                required=True,
                description="The token used to verify your server ownership.",
                example="agricare_secret_token"
            ),
            openapi.Parameter(
                name='hub.challenge',
                in_=openapi.IN_QUERY,
                type=openapi.TYPE_STRING,
                required=True,
                description="A random string/number sent by the provider that your server must echo back.",
                example="123456"
            ),
        ],
        responses={
            200: openapi.Response(
                description="Success. Returns back the exact value sent in hub.challenge.",
                examples={"text/plain": "123456"}
            ),
            403: "Verification Token Mismatch"
        }
    )
    def get(self, request):
        """
        Required for Meta WhatsApp Business API Webhook Verification.
        """
        verify_token = os.environ.get("WHATSAPP_VERIFY_TOKEN", "agricare_secret_token")
        mode = request.GET.get('hub.mode')
        token = request.GET.get('hub.verify_token')
        challenge = request.GET.get('hub.challenge')

        if mode == 'subscribe' and token == verify_token:
            return HttpResponse(challenge)
        return HttpResponse("Verification Token Mismatch", status=403)
